FROM python:3.12-slim

RUN apt-get update &&\
    apt-get install -y procps &&\
    pip install azure-eventhub azure-identity

WORKDIR /app-sender

COPY sender.py /app-sender/

CMD exec python -u sender.py