FROM python:3.12-slim

RUN apt-get update &&\
    apt-get install -y procps &&\
    pip install azure-eventhub azure-identity

WORKDIR /app-receiver

COPY receiver.py /app-receiver/

CMD exec python -u receiver.py